version: "3.7"

services:
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - "./configuration/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./configuration/nginx/common.conf:/etc/nginx/common.conf:ro"
            - "./configuration/nginx/server.conf:/etc/nginx/server.conf:ro"
            - ".:/app"
        networks:
            - nginx-net
        links:
            - backend
        ports:
            - "127.0.0.1:8000:80"

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: "sh ./configuration/gunicorn/django-dev.sh"
        volumes:
            - ".:/app"
        depends_on:
            - db
        networks:
            - db-net
            - nginx-net
        environment:
            PYTHONUNBUFFERED: 1
    db:
        image: postgres:11
        environment:
            POSTGRES_MULTIPLE_DATABASES: debates_tournament
            POSTGRES_USER: tabmaker
            POSTGRES_PASSWORD: 123456
            PG_DATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "./configuration/postgres:/docker-entrypoint-initdb.d"
            - "./dump:/dump"
        networks:
            - db-net
        ports:
            - "5432:5432"
networks:
    db-net:
    nginx-net:
